name = GroupUp
description = A simple 3 column layout demonstrating mobile first and Singularity.
preview = preview.png
template = groupup-layout

; Regions
regions[slider]          = Slider
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/groupup/groupup.layout.css
